[".local/share/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    refreshPeriod = "168h"

[".local/share/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

[".local/share/fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"

[".local/share/zsh-fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
